export const Epath = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-passoword",
  CHANGE_PASSWORD: "/change-password",
  HOME: "/",
  PROFILE: "/profile",
  REGISTER_MONEY: "/register-money",
  FAMILY_TREE: "/family-tree/:clanId",
  CLAN: "/clan/:clanId",
  CLAN_INFORMATION: "/information/:clanId",
  MEMBERS: "/member/:clanId",
  NOT_FOUND_MEMER: "/member",
  NOT_FOUND_CLAN_INFORMATION: "/information",
  NOT_FOUND_EVENT: "/event",
  NOT_FOUND_FAMILY_TREE: "/family-tree",
  EVENT: "/event/:clanId",
};
